FORMAT: 1A

# YukiaSchedulingService


# Group Schedules

## Schedules Control [/api/schedule]

### Get All Schedule [GET]
全てのスケジュールを取得します

+ Request JSON Message

    + Headers
    
            Authorization: Bearer <Token>
                
+ Response 200 (application/json)

    + Attributes(ScheduleResponse)
    
### Create New Schedule [POST]
新しいスケジュールを作成します

+ Request JSON Message

    + Headers
    
            Authorization: Bearer <Token>
    
    + Attributes(ScheduleRequest)
                
+ Response 201 (application/json)

    + Attributes(ScheduleResponse)
    

## Single Schedule Control [/api/schedule/{?schedule_id}]

### Get Single Schedule [GET]
IDで指定されたスケジュールを取得します

+ Request JSON Message

    + Headers
    
            Authorization: Bearer <Token>
                
+ Response 200 (application/json)

    + Attributes(ScheduleResponse)
    
### Update Schedule [PUT]
IDで指定されたスケジュールを更新します

+ Request JSON Message

    + Headers
    
            Authorization: Bearer <Token>
    
    + Attributes(ScheduleRequest)
                
+ Response 204 (application/json)

### Delete Schedule [DELETE]
IDで指定されたスケジュールを削除します

+ Request JSON Message

    + Headers
    
            Authorization: Bearer <Token>
    
    + Attributes(ScheduleRequest)
                
+ Response 204 (application/json)
    
    
# Data Structure

## ScheduleRequest
+ starttime: `"2017-07-20 12:00:00"` (string, optional) - 開始時間（詳細は上記参照）
+ endtime: `"2017-07-20 13:00:00"` (string, optional) - 終了時間（詳細は上記参照）
+ content: "お昼ごはんを食べる"(string, required) - スケジュールの内容

## ScheduleResponse
+ twitter_id: "851775112453828610" (string, required) - ユーザーのTwitterID
+ schedule_id: 1 (number, required) - 各ユーザー毎のスケジュールの連番
+ category: 0 (number, required) - カテゴリー（詳細は上記参照）
+ starttime: `"2017-07-20T12:00:00.0000000+09:00"` (string, required) - 開始時間（詳細は上記参照）
+ endtime: `"2017-07-20T13:00:00.000000009:00"` (string, required) - 終了時間（詳細は上記参照）
+ content: "お昼ごはんを食べる"(string, required) - スケジュールの内容