FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# YukiaSchedulingService
スケジュールを各ユーザー毎に作成、取得、更新、削除（CURD操作）出来るサービスです。
本APIはスケジュールのCURD操作のみを提供し、その他はクライアント開発者に任せる方針を取っています。

【認証】
各ユーザーは、クライアントの初回起動のみTwitterで認証し、
2回目以降はこちらが発行するトークンを利用してユーザーを識別します。
各ユーザーとスケジュールはTwitterIDと紐付いている為、
エンドユーザーから見れば別のクライアントでも同じようにアクセス出来ます。

【各スケジュールのカテゴリーと開始時間・終了時間の関係】
本サービスでは、開始時間(StartTime)・終了時間(EndTime)の有無によりスケジューリングを４つに自動分類しています。
括弧内の数字はレスポンスのカテゴリー番号です。
StartTimeとEndTimeがどちらも存在しない：TODO(0)
StartTimeが存在し、EndTimeが存在しない：Notify(1)
EndTimeが存在し、StartTimeが存在しない：Deadline(2)
StartTimeとEndTimeがどちらも存在する　：Schedule(3)

※現在開発中の為、予告なく仕様が変更される可能性があります。


# スケジュール

## スケジュール全体操作 [api/schedule]

### 全スケジュール取得 [GET]
    + Request
        + Header
            Authorization: Bearer <このサービスのトークン>
    + Response 200 (application/json)
        + Attribute(ScheduleResponse)

### スケジュール作成 [POST]
    + Request
        + Header
            Authorization: Bearer <このサービスのトークン>
        + Attribute(ScheduleRequest)

    + Response 201 (application/json)
        + Attribute(ScheduleResponse)

## 各スケジュール操作 [api/schedule{?id}]

### スケジュール取得 [GET]
    + Request
        + Header
            Authorization: Bearer <このサービスのトークン>
    + Response 200 (application/json)
        + Attribute(ScheduleResponse)

### スケジュール更新 [PUT]
    + Request
        + Header
            Authorization: Bearer <このサービスのトークン>
        + Attribute(ScheduleRequest)

    + Response 204

### スケジュール削除 [DELETE]
    + Request
        + Header
            Authorization: Bearer <このサービスのトークン>
        + Attribute(ScheduleRequest)

    + Response 204
        

# Data Structure

## ScheduleRequest
    + starttime: "2017-07-20 12:00:00" (string, datetime, optional) - 開始時間（詳細は上記参照）
    + endtime: "2017-07-20 13:00:00" (string, datetime, optional) - 終了時間（詳細は上記参照）
    + content: "お昼ごはんを食べる"(string, required) - スケジュールの内容
## ScheduleResponse
    + twitter_id: "851775112453828610" (string, required) - TwitterID
    + schedule_id: 1 (int, required) - 各ユーザー毎のスケジュールの連番
    + category: 0 (int, required) - カテゴリー（詳細は上記参照）
    + starttime: "2017-07-20T12:00:00.0000000+09:00" (string, datetime, required) - 開始時間（詳細は上記参照）
    + endtime: "2017-07-20T13:00:00.0000000+09:00" (string, datetime, required) - 終了時間（詳細は上記参照）
    + content: "お昼ごはんを食べる"(string, required) - スケジュールの内容
